# Generated by Django 4.0.2 on 2022-05-17 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mail',
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'Agent'), ('3 ', 'Customer')], default=1, max_length=50),
        ),
    ]
