# Generated by Django 4.0.2 on 2022-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0002_remove_customer_customer_name_remove_customer_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'Agent'), ('3', 'Customer')], default=1, max_length=50),
        ),
    ]
