# Generated by Django 4.0.2 on 2022-06-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0006_bookplot_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='superagent',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
