# Generated by Django 4.0.2 on 2022-06-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0007_superagent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='superagent',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
