# Generated by Django 4.0.2 on 2022-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0008_superagent_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
