# Generated by Django 4.0.2 on 2022-06-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrixapp', '0009_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
    ]
